#BMI (Body Mass Index) = weight / (height * height)
weight = float(input("enter weight in kg:"))
height = float(input("enter height in m : "))
BMI = weight / (height*height)
print(f"BMI is {BMI}")