# Perimeter of Rectangle = 2 * (length + breadth)
length = float(input("enter the length of the rectangle:"))
breadth = float(input("enter the breadth of the rectangle:"))
perimeter = 2*(length + breadth)
print(f"the perimeter of the rectangle is {perimeter} ")